export const blockedWords = [
  "死ね",
  "しね",
  "氏ね",
  "消えろ",
  "きえろ",
  "くたばれ",
  "ころす",
  "殺す",
  "ばか",
  "バカ",
  "馬鹿",
  "あほ",
  "アホ",
  "阿呆",
  "まぬけ",
  "間抜け",
  "無能",
  "うざい",
  "うぜえ",
  "きもい",
  "キモい",
  "きしょい",
  "クズ",
  "くず",
  "ゴミ",
  "ごみ",
  "カス",
  "かす",
  "ブス",
  "ぶす",
  "デブ",
  "でぶ",
  "ハゲ",
  "はげ",
  "チビ",
  "ちび",
  "雑魚",
  "ざこ",
  "弱虫",
  "殺",
  "くそ",
  "クソ",
  "糞",
  "うんこ",
  "ウンコ",
  "ちんこ",
  "まんこ",
  "おっぱい",
  "セックス",
  "sex",
  "fuck",
  "shit",
  "bitch",
  "asshole",
  "dick",
  "pussy",
  "porn",
  "idiot",
  "stupid",
  "dumb",
  "moron",
  "loser",
  "trash",
  "garbage",
  "ugly",
  "creep",
  "hate",
  "https",
  "http",
  "www.",
];

const blockedWordSeparator = "[\\s\\p{P}\\p{S}_ー～〜・]*";
const looseWordPattern = (...parts) => new RegExp(parts.join(blockedWordSeparator), "iu");

export const blockedWordPatterns = [
  looseWordPattern("f", "(?:u|v|\\*)?", "c", "k"),
  looseWordPattern("s", "(?:h|#)?", "(?:i|1|!|\\*)", "t"),
  looseWordPattern("b", "(?:i|1|!|\\*)", "t", "c", "h"),
  looseWordPattern("a", "(?:s|\\$|5)", "(?:s|\\$|5)", "h", "(?:o|0)", "l", "e"),
  looseWordPattern("d", "(?:i|1|!|\\*)", "c", "k"),
  looseWordPattern("p", "(?:u|v|\\*)", "(?:s|\\$|5)", "(?:s|\\$|5)", "(?:y|¥)"),
  looseWordPattern("s", "(?:e|3)", "x"),
  looseWordPattern("p", "(?:o|0)", "r", "n"),
];

export const brushColors = [
  { name: "コーラル", value: "#ff5f45" },
  { name: "サンセット", value: "#ff8a3d" },
  { name: "レモン", value: "#f8d84a" },
  { name: "ライム", value: "#9be564" },
  { name: "ミント", value: "#35d6a6" },
  { name: "ラグーン", value: "#2aa7d7" },
  { name: "ディープブルー", value: "#2454d6" },
  { name: "ラベンダー", value: "#9b6df3" },
  { name: "ピンク", value: "#ff6fb1" },
  { name: "ホワイト", value: "#ffffff" },
  { name: "グレー", value: "#8ca3a8" },
  { name: "ブラック", value: "#14212b" },
];

export const brushSizeRange = {
  min: 4,
  max: 52,
  defaultValue: 18,
};

export const fillToleranceRange = {
  min: 0,
  max: 72,
  defaultValue: 18,
};

export const defaultFishPayload = {
  species: "original",
  main_color: "#ffffff",
  sub_color: "#ffffff",
  pattern: "none",
  size: "medium",
  personality: "calm",
};
