// Curated from public profanity lists for a child-facing nickname field.
// Sources reviewed:
// - https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words (CC BY 4.0)
// - https://github.com/coffee-and-fun/google-profanity-words (MIT)
export const blockedNicknameContainsTerms = [
  "死ね",
  "しね",
  "氏ね",
  "ﾀﾋね",
  "タヒね",
  "消えろ",
  "きえろ",
  "くたばれ",
  "しんじまえ",
  "死んじまえ",
  "ころす",
  "殺す",
  "殺せ",
  "殺害",
  "殺人",
  "自殺",
  "ばか",
  "馬鹿",
  "ばかやろう",
  "あほ",
  "阿呆",
  "まぬけ",
  "間抜け",
  "のろま",
  "どじ",
  "無能",
  "うざい",
  "うぜえ",
  "うるさい",
  "だまれ",
  "黙れ",
  "きもい",
  "きしょい",
  "くず",
  "ごみ",
  "かす",
  "ぶす",
  "でぶ",
  "はげ",
  "ちび",
  "雑魚",
  "ざこ",
  "弱虫",
  "腰抜け",
  "嘘つき",
  "ぼけ",
  "最低",
  "意地悪",
  "くそがき",
  "くそ",
  "糞",
  "うんこ",
  "ちんこ",
  "ちんぽ",
  "ちんちん",
  "まんこ",
  "おっぱい",
  "オナニー",
  "エロ",
  "エッチ",
  "変態",
  "スケベ",
  "淫乱",
  "やりまん",
  "レイプ",
  "強姦",
  "ポルノ",
  "セックス",
  "ファック",
  "ビッチ",
  "ディック",
  "ニガー",
  "ネオナチ",
  "卍",
  "操你",
  "去死",
  "傻逼",
  "妈的",
  "狗屎",
  "垃圾",
  "废物",
  "婊子",
  "混蛋",
  "王八蛋",
  "fuck",
  "fucker",
  "fucking",
  "motherfuck",
  "shit",
  "bullshit",
  "bitch",
  "asshole",
  "dick",
  "douche",
  "douchebag",
  "bastard",
  "slut",
  "whore",
  "porn",
  "porno",
  "murder",
  "suicide",
  "nazi",
  "neonazi",
  "swastika",
  "idiot",
  "stupid",
  "dumb",
  "moron",
  "loser",
  "trash",
  "garbage",
  "ugly",
  "creep",
  "hate",
  "retard",
  "https",
  "http",
  "www",
];

export const blockedNicknameExactTerms = [
  "ass",
  "arse",
  "crap",
  "damn",
  "hell",
  "sex",
  "rape",
  "rapist",
  "raping",
  "kill",
  "killer",
  "xxx",
  "die",
  "kys",
  "sob",
  "hoe",
  "ho",
  "fag",
  "coon",
  "kike",
  "spic",
  "chink",
  "gook",
  "nigger",
  "nigga",
  "n1gga",
  "n1gger",
  "paki",
  "tranny",
  "屎",
  "滚",
  "操",
  "靠",
  "日",
];

const separator = "[\\s\\p{P}\\p{S}\\u200B-\\u200D\\uFEFF_ー～〜・]*";
const looseWordPattern = (...parts) => new RegExp(parts.join(separator), "iu");

export const blockedNicknamePatterns = [
  looseWordPattern("f", "(?:u|v|\\*)?", "c", "k"),
  looseWordPattern("f", "u", "k"),
  looseWordPattern("f", "c", "u", "k"),
  looseWordPattern("p", "h", "u", "c", "k"),
  looseWordPattern("s", "(?:h|#)?", "(?:i|1|!|\\*)", "t"),
  looseWordPattern("b", "(?:i|1|!|\\*)", "t", "c", "h"),
  looseWordPattern("a", "(?:s|\\$|5)", "(?:s|\\$|5)", "h", "(?:o|0)", "l", "e"),
  looseWordPattern("d", "(?:i|1|!|\\*)", "c", "k"),
  looseWordPattern("p", "(?:u|v|\\*)", "(?:s|\\$|5)", "(?:s|\\$|5)", "(?:y|¥)"),
  looseWordPattern("s", "(?:e|3)", "x"),
  looseWordPattern("p", "(?:o|0)", "r", "n"),
  looseWordPattern("n", "(?:i|1|!|\\*)", "g", "g", "(?:a|e|3|@)"),
  looseWordPattern("c", "(?:u|v|\\*)", "n", "t"),
];
